apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-reverse-geocoder

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml

configMapGenerator:
  - name: local-reverse-geocoder-config
    behavior: merge
    literals:
      - REPLICAS="2"
      - CPU_REQUEST="100m"
      - CPU_LIMIT="" # Empty string means no limit
      - MEMORY_REQUEST="128Mi"
      - MEMORY_LIMIT="256Mi"
