apiVersion: v1
kind: Service
metadata:
  name: local-reverse-geocoder
spec:
  selector:
    app: local-reverse-geocoder
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  type: ClusterIP
